CREATE TABLE PERSON (
    ID UUID PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    GENDER VARCHAR(255) NOT NULL,
    IS_DELETED BOOLEAN NOT NULL
);