CREATE TABLE QUESTIONNAIRE (
    ID UUID NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    IS_DELETED BOOLEAN NOT NULL,
    CONSTRAINT PK_QUESTIONNAIRE PRIMARY KEY (ID),
    CONSTRAINT UNIQUE_QUESTIONNAIRE_NAME UNIQUE (NAME)
);

CREATE TABLE QUESTIONNAIRE_ITEM (
    QUESTIONNAIRE_ID UUID NOT NULL,
    ITEM_ID UUID NOT NULL,
    CONSTRAINT PK_QUESTIONNAIRE_ITEM PRIMARY KEY (QUESTIONNAIRE_ID, ITEM_ID),
    CONSTRAINT FK_QUESTIONNAIRE_ITEM_QUESTIONNAIRE_ID FOREIGN KEY (QUESTIONNAIRE_ID) REFERENCES QUESTIONNAIRE(ID),
    CONSTRAINT FK_QUESTIONNAIRE_ITEM_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ID)
);

CREATE TABLE COMPLETED_QUESTIONNAIRE (
    ID UUID NOT NULL,
    QUESTIONNAIRE_ID UUID NOT NULL,
    PERSON_ID UUID,
    CONSTRAINT PK_COMPLETED_QUESTIONNAIRE PRIMARY KEY (ID),
    CONSTRAINT FK_COMPLETED_QUESTIONNAIRE_QUESTIONNAIRE_ID FOREIGN KEY (QUESTIONNAIRE_ID) REFERENCES QUESTIONNAIRE(ID),
    CONSTRAINT FK_COMPLETED_QUESTIONNAIRE_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID)
);

CREATE TABLE COMPLETED_QUESTIONNAIRE_ITEM_RESPONSE (
    COMPLETED_QUESTIONNAIRE_ID UUID NOT NULL,
    ITEM_RESPONSE_ITEM_ID UUID NOT NULL,
    ITEM_RESPONSE_RESPONSE VARCHAR(256) NOT NULL,
    CONSTRAINT PK_COMPLETED_QUESTIONNAIRE_ITEM_RESPONSE PRIMARY KEY (COMPLETED_QUESTIONNAIRE_ID, ITEM_RESPONSE_ITEM_ID),
    CONSTRAINT FK_COMPLETED_QUESTIONNAIRE_ITEM_RESPONSE_COMPL_QUESTION_ID FOREIGN KEY (COMPLETED_QUESTIONNAIRE_ID) REFERENCES COMPLETED_QUESTIONNAIRE(ID),
    CONSTRAINT FK_COMPLETED_QUESTIONNAIRE_ITEM_RESPONSE_ITEM_ID_RESPONSE FOREIGN KEY (ITEM_RESPONSE_ITEM_ID, ITEM_RESPONSE_RESPONSE) REFERENCES ITEM_RESPONSE(ITEM_ID, RESPONSE)
);